depracet yaml.load method
https://bobbyhadz.com/blog/python-typeerror-load-missing-1-required-positional-argument-loader

.local/lib/python3.9/site-packages/tailon/main.py", line 61, in parseconfig
    raw_config = yaml.load(cfg)
TypeError: load() missing 1 required positional argument: 'Loader'